/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication21;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication21.AddData.openFile;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.PrintSetup;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author kedar
 */
public class MaktedarData extends javax.swing.JFrame {

    Config config;
    String tableNames[] = {"अपारंपारिक_उर्जा", "इतर_जिल्हा_रस्ते_विकास_व_मजबुतीकरण", "ग्रामीण_रस्ताचा_विकास_वा_मजबुती_करण", "जिल्हा_नियोजन_मागणी_ओ_283451_सचिवालय_आर्थिक_सेवा", "नावीन्यपूर्ण_योजना"};
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form MaktedarData
     */
    public MaktedarData() {
        initComponents();
        config = new Config();
        AutoCompleteDecorator.decorate(contractorComboBox);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contractorComboBox = new javax.swing.JComboBox<>();
        showContractorBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contractorTable = new javax.swing.JTable();
        yearChooseCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        exportToExcelBtn = new javax.swing.JButton();
        closeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setFont(new java.awt.Font("Mangal", 0, 12)); // NOI18N

        contractorComboBox.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        contractorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "मक्तेदार निवडणे" }));

        showContractorBtn.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        showContractorBtn.setText("दाखवा");
        showContractorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showContractorBtnActionPerformed(evt);
            }
        });

        contractorTable.setFont(new java.awt.Font("Mangal", 0, 12)); // NOI18N
        contractorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "वर्ष", "बांधकाम_विभाग", "तालुका", "योजना", "कामाचे_नांव", "प्रशासकीय_मान्यता_दिनाक", "प्रशासकीय_मान्यता_रक्कम", "तांत्रीक_मान्यता_दिनांक", "तांत्रीक_मान्यता_रक्कम", "मक्तेदाराचे_नांव", "कामाचा_आदेश_व_दिनांक", "निविदा_स्विकृती_रक्कम", "जी_एस_टी", "एकुण", "कामाची_मुदत_महिने", "प्राप्त_निधी_या_वर्षा_मध्ये", "या_वर्षा_मधील_खर्च_जी_एस_टी_सह", "काम_पूर्ण_झालेल्याचे_तारिक", "शेरा"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        contractorTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(contractorTable);

        yearChooseCombo.setFont(new java.awt.Font("Mangal", 0, 14)); // NOI18N
        yearChooseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "वर्ष निवडा", "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026" }));
        yearChooseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearChooseComboActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "कृती", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Mangal", 1, 14))); // NOI18N

        exportToExcelBtn.setFont(new java.awt.Font("Mangal", 0, 13)); // NOI18N
        exportToExcelBtn.setText("विभाग एक्सेल मध्ये ");
        exportToExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportToExcelBtnActionPerformed(evt);
            }
        });

        closeBtn1.setFont(new java.awt.Font("Mangal", 0, 13)); // NOI18N
        closeBtn1.setText("बंद करा");
        closeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(exportToExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(closeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportToExcelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contractorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showContractorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(yearChooseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(414, 414, 414))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(yearChooseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showContractorBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showContractorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showContractorBtnActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) contractorTable.getModel();
            model.setRowCount(0);

            String contractorName = contractorComboBox.getSelectedItem().toString();
            String yearChooseContractor = yearChooseCombo.getSelectedItem().toString();
            int tableLength = tableNames.length;
            Statement stmtContractor[] = new Statement[tableLength];
            ResultSet rsContractor[] = new ResultSet[tableLength];

            for (int i = 0; i < tableLength; i++) {
                stmtContractor[i] = config.conn.createStatement();
                rsContractor[i] = stmtContractor[i].executeQuery("SELECT * FROM एमपीआर." + tableNames[i] + " WHERE वर्ष = N'" + yearChooseContractor + "' AND मक्तेदाराचे_नांव = N'" + contractorName + "';");
                while (rsContractor[i].next()) {
                    Object tblData[] = {rsContractor[i].getString("वर्ष"), rsContractor[i].getString("बांधकाम_विभाग"), rsContractor[i].getString("तालुका"), tableNames[i], rsContractor[i].getString("कामाचे_नांव"), rsContractor[i].getString("प्रशासकीय_मान्यता_दिनाक"), rsContractor[i].getString("प्रशासकीय_मान्यता_रक्कम"), rsContractor[i].getString("तांत्रीक_मान्यता_दिनांक"), rsContractor[i].getString("तांत्रीक_मान्यता_रक्कम"), rsContractor[i].getString("मक्तेदाराचे_नांव"), rsContractor[i].getString("कामाचा_आदेश_व_दिनांक"), rsContractor[i].getString("निविदा_स्विकृती_रक्कम"), rsContractor[i].getString("जी_एस_टी"), rsContractor[i].getString("एकुण"), rsContractor[i].getString("कामाची_मुदत_महिने"), rsContractor[i].getString("प्राप्त_निधी_या_वर्षा_मध्ये"), rsContractor[i].getString("या_वर्षा_मधील_खर्च_जी_एस_टी_सह"), rsContractor[i].getString("काम_पूर्ण_झालेल्याचे_तारिक"), rsContractor[i].getString("शेरा")};

                    defaultTableModel = (DefaultTableModel) contractorTable.getModel();
                    defaultTableModel.addRow(tblData);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Print Data", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_showContractorBtnActionPerformed

    private void yearChooseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearChooseComboActionPerformed
        try {
            // TODO add your handling code here:
            getContractorNames();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Print Data", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_yearChooseComboActionPerformed

    private void exportToExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportToExcelBtnActionPerformed
        // TODO add your handling code here:
        exportToExcel(contractorTable);

    }//GEN-LAST:event_exportToExcelBtnActionPerformed

    private void exportToExcel(JTable jt) {
        try {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(jt);
            File saveFile = jFileChooser.getSelectedFile();
            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet(contractorComboBox.getSelectedItem().toString() + "_" + yearChooseCombo.getSelectedItem().toString());
                sheet.setColumnWidth(0, 1500);

                Row rowHeader = sheet.createRow(0);

                Row rowCol = sheet.createRow(1);
                XSSFFont font = ((XSSFWorkbook) wb).createFont();
                font.setBold(true);

                CellStyle style = wb.createCellStyle();
                style.setFont(font);
                style.setWrapText(true);
                style.setBorderTop(BorderStyle.THIN);
                style.setBorderBottom(BorderStyle.THIN);
                style.setBorderLeft(BorderStyle.THIN);
                style.setBorderRight(BorderStyle.THIN);

                XSSFFont fontHeader = ((XSSFWorkbook) wb).createFont();
                fontHeader.setBold(true);
                fontHeader.setFontHeightInPoints((short) 20);
                CellStyle styleHeader = wb.createCellStyle();
                styleHeader.setFont(fontHeader);
//                styleHeader.setWrapText(true);

                Cell cellHeader = rowHeader.createCell(6);

                cellHeader.setCellStyle(styleHeader);
                cellHeader.setCellValue(contractorComboBox.getSelectedItem().toString() + "_" + yearChooseCombo.getSelectedItem().toString());

                for (int i = 0; i < jt.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellStyle(style);
                    cell.setCellValue(jt.getColumnName(i));
                    sheet.setColumnWidth(i + 1, 4000);

                }
                sheet.setRepeatingRows(CellRangeAddress.valueOf("2:2"));
                Cell cell = null;

                CellStyle styleData = wb.createCellStyle();
                styleData.setWrapText(true);
                styleData.setBorderTop(BorderStyle.THIN);
                styleData.setBorderBottom(BorderStyle.THIN);
                styleData.setBorderLeft(BorderStyle.THIN);
                styleData.setBorderRight(BorderStyle.THIN);

                for (int j = 0; j < jt.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 2);
                    for (int k = 0; k < jt.getColumnCount(); k++) {
                        cell = row.createCell(k);
                        if (jt.getValueAt(j, k) != null) {
                            if (j == 0) {
                                cell.setCellStyle(style);
                            }
                            cell.setCellStyle(styleData);
                            cell.setCellValue(jt.getValueAt(j, k).toString());

                        }

                    }
                }

                Row rowTotal = sheet.createRow(jt.getRowCount() + 2);

                Cell cellTotal = rowTotal.createCell(0);
                cellTotal.setCellValue("एकूण");
                cellTotal.setCellStyle(style);

                long prashashkiyaSum = 0;
                long kharchWithGstSum = 0;
                for (int i = 0; i < jt.getRowCount(); i++) {
                    prashashkiyaSum = (long) (prashashkiyaSum + Long.parseLong(jt.getValueAt(i, 6).toString()));

                    kharchWithGstSum = (long) (kharchWithGstSum + Integer.parseInt(jt.getValueAt(i, 16).toString()));
                }
                System.out.println("prashashkiyaSum Sum : " + prashashkiyaSum);

                Cell prashashkiyaCell = rowTotal.createCell(6);
                prashashkiyaCell.setCellValue(Long.toString(prashashkiyaSum));
                prashashkiyaCell.setCellStyle(style);

                Cell kharchWithGstCell = rowTotal.createCell(16);
                kharchWithGstCell.setCellValue(Long.toString(kharchWithGstSum));
                kharchWithGstCell.setCellStyle(style);

//                PrintSetup printSetup = sheet.getPrintSetup();
                PrintSetup printSetup = sheet.getPrintSetup();
                printSetup.setLandscape(true);
                sheet.setFitToPage(true);
                printSetup.setPaperSize(PrintSetup.LETTER_PAPERSIZE);

                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());

            } else {
                JOptionPane.showMessageDialog(null, "Operation Cancelled", "Monthly Progress Report", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Exception occured : " + ex.toString(), "Monthly Progress Report", JOptionPane.ERROR_MESSAGE);

        }
    }


    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closeBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaktedarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaktedarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaktedarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaktedarData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaktedarData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn1;
    private javax.swing.JComboBox<String> contractorComboBox;
    private javax.swing.JTable contractorTable;
    private javax.swing.JButton exportToExcelBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton showContractorBtn;
    private javax.swing.JComboBox<String> yearChooseCombo;
    // End of variables declaration//GEN-END:variables

    private void getContractorNames() throws SQLException {
        try {

            String yearChoose = yearChooseCombo.getSelectedItem().toString();
            int tablesLength = tableNames.length;
            Statement stmtTables[] = new Statement[tablesLength];
            ResultSet rsTables[] = new ResultSet[tablesLength];
            Set<String> contractorNames = new HashSet<>();

            for (int i = 0; i < tablesLength; i++) {
                stmtTables[i] = config.conn.createStatement();
                rsTables[i] = stmtTables[i].executeQuery("SELECT * FROM एमपीआर." + tableNames[i] + " WHERE वर्ष = N'" + yearChoose + "';");
                while (rsTables[i].next()) {
                    contractorNames.add(rsTables[i].getString("मक्तेदाराचे_नांव"));
                }
            }
            System.out.println("COntractor Names : ");
            System.out.println(contractorNames);

            String[] contractorArray = contractorNames.toArray(new String[0]);
            contractorComboBox.setModel(new DefaultComboBoxModel(contractorArray));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString(), "Print Data", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

}
